### ISSUE TITLE
Moreculling 0.12.3 for 1.19.2 crashing game

### ISSUE THREAD

**Issue by VeggeieDude** [fxmorin/MoreCulling#117]
Heya! Thank you for keeping 1.19.2 updated!

I'm crashing with the newest update though, going back to the previous update still works however.

Here are the logs:
[2022-12-20-2.log](https://github.com/fxmorin/MoreCulling/files/10265543/2022-12-20-2.log)

[00:09:11] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.class_761.method_22979(class_761.java:1558) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1374) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]

This is the only error I see

**Comment by fxmorin** [comment]
Thanks for reporting it. I'm currently not home to check the issues. So I'll have to fix this later

**Comment by VeggeieDude** [comment]
No problem, take your time! Happy holidays!

**Comment by fxmorin** [comment]
I'll be using #118 to track this issue
