### ISSUE TITLE
MoreCulling 0.15.0 for 1.19.2 and 1.19.1 depends on `org.joml.Vector3f` which is only available in Quilt, not Fabric.

### ISSUE THREAD

**Issue by akemin-dayo** [fxmorin/MoreCulling#139]
MoreCulling 0.15.0 for 1.19.2 and 1.19.1 depends on `org.joml.Vector3f` which is only available in Quilt, not Fabric.

Fabric 1.19.3 is unaffected by this issue. Quilt 1.19.3 〜 1.19.1 are unaffected by this issue.

Reproduces with a minimal set of mods consisting of only MoreCulling 0.15.0 and Cloth Config 8.2.88 and nothing else.

## Stack trace
```
Error loading class: org/joml/Vector3f (java.lang.ClassNotFoundException: org/joml/Vector3f)
```

```
java.lang.ExceptionInInitializerError
	at net.minecraft.class_4599.method_22999(class_4599.java:35)
	at net.minecraft.class_156.method_654(class_156.java:448)
	at net.minecraft.class_4599.<init>(class_4599.java:13)
	at net.minecraft.class_310.<init>(class_310.java:570)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_793 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_1088.<clinit>(class_1088.java:155)
	... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for moreculling.mixins.json:models.cullshape.JsonUnbakedModel_cullShapeMixin from mod moreculling during activity: [Transform -> Method onBake(Lnet/minecraft/class_1088;Lnet/minecraft/class_793;Ljava/util/function/Function;Lnet/minecraft/class_3665;Lnet/minecraft/class_2960;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> GETFIELD -> org/joml/Vector3f::x:F]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.joml.Vector3f
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:774)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:737)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.joml.Vector3f
	... 27 more
```

**Comment by fxmorin** [comment]
Thanks for bringing this up, I'll fix it when I find nd some free time

**Comment by fxmorin** [comment]
Ah it only happens when you are not using Sodium, since sodium adds Joml. I'll change it
