### ISSUE TITLE
Culling hanging signs causes crash

### ISSUE THREAD

**Issue by Voldemarvel** [fxmorin/MoreCulling#184]
Anywhere where a hanging sign is rendered causes game to CTD
The following is the crash report.

Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property class_2758{name=rotation, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:oak_wall_hanging_sign}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.minecraft.class_837.cullSignText(class_837.java:579)
	at net.minecraft.class_837.wrapWithCondition$beo000$moreculling$cullFrontSignText(class_837.java:544)
	at net.minecraft.class_837.method_49920(class_837.java:82)
	at net.minecraft.class_7761.method_23083(class_7761.java:77)
	at net.minecraft.class_7761.method_3569(class_7761.java:30)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275)
	at net.minecraft.class_761.handler$bfk000$sodium$onRenderTileEntities(class_761.java:11608)
	at net.minecraft.class_761.method_22710(class_761.java:1372)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Voldemarvel** [comment]
I didn't notice the update...

aplogies.
