### ISSUE TITLE
Hovering over a setting causes a crash

### ISSUE THREAD

**Issue by Paladynee** [fxmorin/MoreCulling#187]
[crash-2023-08-05_06.52.22-client.txt](https://github.com/fxmorin/MoreCulling/files/12266029/crash-2023-08-05_06.52.22-client.txt)

I don't remember which setting, but hovering over it made my game crash. I was using the `Sodium 0.5.0` (new release) video settings UI.

**Comment by znopp** [comment]
Same issue.

**Comment by Alex-MacLean** [comment]
Same issue with Sodium 0.5.0. Looks like the API Sodium uses to draw the config screen has changed. This happened when I clicked on the MoreCulling option in the video settings screen. The screen rendered for roughly one tick then crashed. Here is a bit of my crash log that the launcher chose as the likely error. A full log with the same error is in the initial report. 

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'void ca.fxco.moreculling.config.sodium.IntSliderControl$Button.drawRect(double, double, double, double, int)'

**Comment by JOPATE** [comment]
same here

Time: 2023-08-05 16:24:01
Description: Rendering screen

java.lang.NoSuchMethodError: 'void ca.fxco.moreculling.config.sodium.IntSliderControl$Button.drawRect(double, double, double, double, int)'
	at ca.fxco.moreculling.config.sodium.IntSliderControl$Button.renderSlider(IntSliderControl.java:108)
	at ca.fxco.moreculling.config.sodium.IntSliderControl$Button.method_25394(IntSliderControl.java:77)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:50)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.OptionPageFrame.method_25394(OptionPageFrame.java:104)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:50)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.ScrollableFrame.method_25394(ScrollableFrame.java:125)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.tab.TabFrame.method_25394(TabFrame.java:136)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:50)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.BasicFrame.method_25394(BasicFrame.java:39)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen.method_25394(SodiumVideoOptionsScreen.java:173)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by fxmorin** [comment]
https://github.com/fxmorin/MoreCulling/releases/tag/v0.19.0-1.20.x
