### ISSUE TITLE
crash when scrolling in MoreCulling settings

### ISSUE THREAD

**Issue by MaxxusX** [FxMorin/MoreCulling#189]
game crashes when scrolling in MoreCulling settings

```java
java.lang.NoSuchMethodError: 'void ca.fxco.moreculling.config.sodium.IntSliderControl$Button.drawRect(double, double, double, double, int)'
	at ca.fxco.moreculling.config.sodium.IntSliderControl$Button.renderSlider(IntSliderControl.java:108)
	at ca.fxco.moreculling.config.sodium.IntSliderControl$Button.method_25394(IntSliderControl.java:77)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:50)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.OptionPageFrame.method_25394(OptionPageFrame.java:104)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:50)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.ScrollableFrame.lambda$render$2(ScrollableFrame.java:123)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.applyScissor(AbstractFrame.java:58)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.ScrollableFrame.method_25394(ScrollableFrame.java:123)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.tab.TabFrame.method_25394(TabFrame.java:136)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:50)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.BasicFrame.method_25394(BasicFrame.java:39)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen.method_25394(SodiumVideoOptionsScreen.java:173)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
```
[crash-2023-08-23_22.27.02-client.txt](https://github.com/fxmorin/MoreCulling/files/12425210/crash-2023-08-23_22.27.02-client.txt)

**Comment by ElPepe6969** [comment]
I also get crash but I dont even have to scroll, just hovering with mouse above some settings does that for me

**Comment by fxmorin** [comment]
Are you using the latest version?

**Comment by ElPepe6969** [comment]
I was using the latest quilt version and now that you mentioned it, i switched to the 0.19.0 and it does not crash, but modrinth launcher auto downgrades to 0.18.1 every time I auto update, cause the 0.19.0 is fabric only
![image](https://github.com/fxmorin/MoreCulling/assets/122692226/07ea423c-e2d9-4994-a47b-62b8ff756709)

**Comment by levblob** [comment]
Can confirm the issue solves itself when updating to the latest MoreCulling version (at least on Quilt). Pasting my crash report here so it gets picked up by SEO for people that may have this issue in the future, since it was a different log, but same cause.

	java.lang.NoSuchMethodError: 'void ca.fxco.moreculling.config.sodium.FloatSliderControl$Button.drawRect(double, double, double, double, int)'
	at ca.fxco.moreculling.config.sodium.FloatSliderControl$Button.renderSlider(FloatSliderControl.java:111)
	at ca.fxco.moreculling.config.sodium.FloatSliderControl$Button.method_25394(FloatSliderControl.java:80)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:50)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.OptionPageFrame.method_25394(OptionPageFrame.java:104)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:50)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.ScrollableFrame.method_25394(ScrollableFrame.java:125)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.tab.TabFrame.method_25394(TabFrame.java:136)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.AbstractFrame.method_25394(AbstractFrame.java:50)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.frame.BasicFrame.method_25394(BasicFrame.java:39)
	at me.flashyreese.mods.reeses_sodium_options.client.gui.SodiumVideoOptionsScreen.method_25394(SodiumVideoOptionsScreen.java:173)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
