### ISSUE TITLE
Cloth Config Menu Background Texture Issue

### ISSUE THREAD

**Issue by Finoway** [FxMorin/MoreCulling#192]
**Minecraft Version**: 1.20.1
**Fabric Loader**: 0.14.22

**Mods**:
- Cloth Config v11: 11.1.106
- Fabric API: 0.89.0+1.20.1
- Mod Menu: 7.2.2
- More Culling: 1.20.1-0.19.0

**Issue**:
The Cloth Config menu for configuring the MoreCulling mod is unable to locate the background texture, causing an error.

**Steps to Reproduce**:
1. Install Minecraft with Fabric.
2. Install the mentioned mods.
3. Start the game.
4. Click on "Mods"
5. Click on the MoreCulling configuration button.
6. Observe the background of the menu and the logs.

**Error**:
```
[10:30:39] [Render thread/WARN]: Failed to load texture: minecraft:block/dirt
java.io.FileNotFoundException: minecraft:block/dirt
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:119) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem._setShaderTexture(RenderSystem.java:1232) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:1225) ~[client-intermediary.jar:?]
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.renderBackBackground(DynamicEntryListWidget.java:274) ~[cloth-config-11.1.106-fabric.jar:?]
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen$ListWidget.renderBackBackground(ClothConfigScreen.java:422) ~[cloth-config-11.1.106-fabric.jar:?]
	at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.method_25394(DynamicEntryListWidget.java:299) ~[cloth-config-11.1.106-fabric.jar:?]
	at me.shedaniel.clothconfig2.gui.widget.DynamicSmoothScrollingEntryListWidget.method_25394(DynamicSmoothScrollingEntryListWidget.java:128) ~[cloth-config-11.1.106-fabric.jar:?]
	at me.shedaniel.clothconfig2.gui.ClothConfigScreen.method_25394(ClothConfigScreen.java:235) ~[cloth-config-11.1.106-fabric.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

**Screenshot**:
![image](https://github.com/fxmorin/MoreCulling/assets/48923336/4f27b7b7-83e1-4cfd-b267-36ece02c74fe)

**Comment by Obscure2020** [comment]
I can confirm I am also getting a missing background texture. Fix, please!

**Minecraft Version:** 1.20.4
**Fabric Loader:** 0.15.3

**Relevant Mods:**
- Cloth Config v13.0.121
- Fabric API v0.91.3+1.20.4
- Mod Menu v9.0.0
- More Culling v1.20.1-0.19.0

![2023-12-26_23 49 35](https://github.com/FxMorin/MoreCulling/assets/69320464/c5a098d9-5272-40b7-8044-38ae12cce031)

**Comment by FxMorin** [comment]
Will be fixed in the next release
