### ISSUE TITLE
Crash with Lambdabettergrass (1.20.1 Quilt)

### ISSUE THREAD

**Issue by SteamWo1f** [FxMorin/MoreCulling#198]
While attempting to initiate a game using the [More Culling (version 1.20.1-0.19.0)](https://modrinth.com/mod/moreculling/version/v0.19.0-1.20.x) and [LambdaBetterGrass (version 1.5.2+1.20.1)](https://modrinth.com/mod/lambdabettergrass/version/1.5.2+1.20.1) mods on [Quilt (version 0.23.0-beta.1)](https://github.com/QuiltMC/quilt-loader/releases/tag/0.23.0-beta.1), the game unexpectedly terminates. 

Here is the crash error report:

```
java.lang.NullPointerException: Cannot invoke "ca.fxco.moreculling.api.model.BakedOpacity.getCullingShape(net.minecraft.class_2680)" because the return value of "net.minecraft.class_776.method_3349(net.minecraft.class_2680)" is null
	at net.minecraft.class_4970$class_4971$class_3752.redirect$fmo000$moreculling$customCullingShape(class_4970.java:1906)
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1287)
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:843)
	at net.minecraft.class_4970$class_4971.mfix$generateCache(class_4970.java:2370)
	at net.minecraft.class_4970$class_4971.redirect$bmn000$modernfix$dynamicCacheGen(class_4970.java:2389)
	at net.minecraft.class_4970$class_4971.method_26216(class_4970.java:1009)
	at me.pepperbell.continuity.client.resource.CustomBlockLayers.getLayer(CustomBlockLayers.java:45)
	at net.minecraft.class_4696.handler$bdm000$continuity$onHeadGetBlockLayer(class_4696.java:519)
	at net.minecraft.class_4696.method_23679(class_4696.java)
	at dev.lambdaurora.lambdabettergrass.metadata.LBGLayerType.apply(LBGLayerType.java:106)
	at dev.lambdaurora.lambdabettergrass.metadata.LBGLayerState.putOrReplaceMetadata(LBGLayerState.java:120)
	at dev.lambdaurora.lambdabettergrass.metadata.LBGLayerState.lambda$loadVariant$1(LBGLayerState.java:81)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at dev.lambdaurora.lambdabettergrass.metadata.LBGLayerType.forEach(LBGLayerType.java:128)
	at dev.lambdaurora.lambdabettergrass.metadata.LBGLayerState.loadVariant(LBGLayerState.java:80)
	at dev.lambdaurora.lambdabettergrass.metadata.LBGLayerState.lambda$new$0(LBGLayerState.java:65)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at dev.lambdaurora.lambdabettergrass.metadata.LBGLayerState.<init>(LBGLayerState.java:62)
	at dev.lambdaurora.lambdabettergrass.metadata.LBGState.loadMetadataState(LBGState.java:109)
	at dev.lambdaurora.lambdabettergrass.resource.LBGResourceReloader.loadState(LBGResourceReloader.java:76)
	at dev.lambdaurora.lambdabettergrass.resource.LBGResourceReloader.lambda$loadStates$2(LBGResourceReloader.java:50)
	at java.base/java.util.TreeMap.forEach(TreeMap.java:1282)
	at dev.lambdaurora.lambdabettergrass.resource.LBGResourceReloader.loadStates(LBGResourceReloader.java:50)
	at dev.lambdaurora.lambdabettergrass.resource.LBGResourceReloader.reload(LBGResourceReloader.java:43)
	at dev.lambdaurora.lambdabettergrass.LambdaBetterGrass.lambda$onInitializeClient$1(LambdaBetterGrass.java:68)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.lambda$createResourcePackRegistrationEvent$0(ResourceLoaderImpl.java:114)
	at org.quiltmc.qsl.resource.loader.impl.ResourceLoaderImpl.appendTopPacks(ResourceLoaderImpl.java:227)
	at net.minecraft.class_6861.quilt$appendTopPacks(class_6861.java:2582)
	at net.minecraft.class_3304.handler$glm000$quilt_resource_loader$reload(class_3304.java:3062)
	at net.minecraft.class_3304.method_18232(class_3304.java:47)
	at net.minecraft.class_310.<init>(class_310.java:652)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

Thank you for reading.

**Comment by FxMorin** [comment]
This will be fixed in the next release
