### ISSUE TITLE
Game crashes a few seconds after loading a world with Sodium 6.0

### ISSUE THREAD

**Issue by smiRaphi** [FxMorin/MoreCulling#275]
The game crashes a few moments after loading a world with More Culling 0.26.0 and Sodium 0.6.0-alpha.3-mc1.21 (also happens on 0.6.0-beta.1).
This doesn't happen with leavesCullingMode set to FAST.

Log:
```
java.lang.RuntimeException: Exception thrown while executing job
	at net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at net.caffeinemc.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:384)
	at net.caffeinemc.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:294)
	at net.caffeinemc.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:235)
	at net.minecraft.class_761.method_3273(class_761.java:16783)
	at net.minecraft.class_761.method_22710(class_761.java:983)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/SodiumClientMod
	at ca.fxco.moreculling.utils.CullingUtils.areLeavesOpaque(CullingUtils.java:92)
	at net.minecraft.class_2397.method_9522(class_2397.java:1537)
	at net.minecraft.class_4970$class_4971.method_26187(class_4970.java:1050)
	at net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockOcclusionCache.shouldDrawSide(BlockOcclusionCache.java:48)
	at net.caffeinemc.mods.sodium.client.render.frapi.render.AbstractBlockRenderContext.isFaceCulled(AbstractBlockRenderContext.java:140)
	at me.pepperbell.continuity.client.model.CtmBakedModel$CtmQuadTransform.transform(CtmBakedModel.java:100)
	at net.caffeinemc.mods.sodium.client.render.frapi.render.AbstractRenderContext.transform(AbstractRenderContext.java:47)
	at net.caffeinemc.mods.sodium.client.render.frapi.render.AbstractBlockRenderContext.renderQuad(AbstractBlockRenderContext.java:167)
	at net.caffeinemc.mods.sodium.client.render.frapi.render.AbstractBlockRenderContext.bufferDefaultModel(AbstractBlockRenderContext.java:253)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1521)
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
	at net.minecraft.class_1095.emitBlockQuads(class_1095.java:601)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at me.pepperbell.continuity.client.model.CtmBakedModel.emitBlockQuads(CtmBakedModel.java:53)
	at net.caffeinemc.mods.sodium.client.render.chunk.compile.pipeline.BlockRenderer.renderModel(BlockRenderer.java:96)
	at net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:112)
	at net.caffeinemc.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:50)
	at net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:45)
	at net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:213)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.SodiumClientMod
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.caffeinemc.mods.sodium.client.render.chunk.compile.executor.ChunkJobResult.unwrap(ChunkJobResult.java:27)
	at net.caffeinemc.mods.sodium.client.render.chunk.RenderSectionManager.collectChunkBuildResults(RenderSectionManager.java:384)
	at net.caffeinemc.mods.sodium.client.render.chunk.RenderSectionManager.uploadChunks(RenderSectionManager.java:294)
	at net.caffeinemc.mods.sodium.client.render.SodiumWorldRenderer.setupTerrain(SodiumWorldRenderer.java:235)
	at net.minecraft.class_761.method_3273(class_761.java:16783)
	at net.minecraft.class_761.method_22710(class_761.java:983)
	at net.minecraft.class_757.method_3188(class_757.java:1087)

-- Uptime --
Details:
	JVM uptime: 163.977s
	Wall uptime: 154.312s
	High-res time: 150.360s
	Client ticks: 1833 ticks / 91.650s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['smiRaphi'/16, l='ClientLevel', x=-921.56, y=144.00, z=33.85]]
	Chunk stats: 2209, 1469
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,95,48), Section: (at 0,15,0 in -2,5,3; chunk contains blocks -32,-64,48 to -17,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 182297 game time, 60664 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 46
```

**Comment by tajemniktv** [comment]
Dev versions of sodium are not supported by many mods, your options are to either downgrade Sodium or to seek dev versions of mods that would support Sodium Alpha. 
Continuity is also referenced in the logs, might be also the cause of this

**Comment by smiRaphi** [comment]
I need this version of sodium for distant horizon in 1.21.1 and nearly all mods that I use already support it, the only ones that don't are physics mod (on fabric at least), bobby, sodium extra & more culling
I've also just tested it without Continuity and nothing changes, it's still crashing in the same way.

**Comment by tajemniktv** [comment]
Aw, in that case I highly doubt anything can be done for now - Especially as it looks like FxMorin doesn't have too much time to take care of the stable version of MoreCulling. 

One thing I can think of is playing with Culling settings, maybe turning one of these off, would stop crashing the game. Other way could be to try to remove BakedQuad mixin and build it yourself to check whether that helps in any way. On the other hand, that could possibly create some unexpected results and or other issues

For now, without official support support for neither Sodium Alphas nor 1.21.1, it might be impossible to get MoreCulling to work, without getting deeper into this issue

**Comment by shadowtigercool** [comment]
Also broken on 0.6.0-beta.1 (https://modrinth.com/mod/sodium/version/mc1.21-0.6.0-beta.1-fabric)

**Comment by tajemniktv** [comment]
Seems to be working fine for me? Would you mind sending your logs?
