### ISSUE TITLE
0.27 is still incompatible with Sodium 0.6

### ISSUE THREAD

**Issue by Oregano1963** [FxMorin/MoreCulling#280]
Error:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'More Culling' (moreculling) 0.27.0 with any version that is compatible with:
		 - sodium 0.6.0-beta.1+mc1.21
More details:
	 - Mod 'More Culling' (moreculling) 0.27.0 is incompatible with any version before 0.6.0 of mod 'Sodium' (sodium), but a matching version is present: 0.6.0-beta.1+mc1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

**Comment by FxMorin** [comment]
Fixed in v0.27.1
