### ISSUE TITLE
Incompatible with Cloth Config 8.0.75

### ISSUE THREAD

**Issue by NaiNonTH** [fxmorin/MoreCulling#61]
I'll let the error log tells you.
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'More Culling' (moreculling) 1.19.1-0.8.1 with any version that is compatible with:
		 - cloth-config 8.0.75
Unmet dependency listing:
	 - Mod 'More Culling' (moreculling) 1.19.1-0.8.1 requires any 7.x version of mod 'Cloth Config v8' (cloth-config), which can't be loaded due to other constraints!
	 - Mod 'Tinfoiled Cotton Client Commands' (cotton-client-commands) 1.1.0+1.15.2 requires any version between 1.14- (inclusive) and 1.16- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.1!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.8+13-main requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.1!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.8+13-main requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.1!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.8+13-main requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.1!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.8+13-main requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.1!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc118) 0.4.8+13-main requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Ignore Tinfoiled and ViaFabric stuff; they work completely fine without this issue.

**Comment by NaiNonTH** [comment]
Ah, and here's the log
[latest.log](https://github.com/fxmorin/MoreCulling/files/9228956/latest.log)

**Comment by NaiNonTH** [comment]
Closing the issue, opening a new issue.
